name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./ -Recurse -Severity Error -EnableExit

  windows:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-windows.yml@00ff10246f901f01818db412fa99124dbed4a00c
    strategy:
      matrix:
        os_version:
          - windows-2019
          - windows-2022
          - windows-2025
        salt_state:
          - notepad-plusplus
        salt_pillar_root:
          - ./tests/pillar/test-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
