name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-windows.yml@00ff10246f901f01818db412fa99124dbed4a00c
    strategy:
      matrix:
        os_version:
          - windows-2019
          - windows-2022
          - windows-2025
        salt_state:
          - notepad-plusplus
        salt_pillar_root:
          - ./tests/pillar/test-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}

  lint_powershell:
    name: PowerShell Linting
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path ./ -Include *.ps1 -Recurse
          Write-Host "Found $($files.Count) PowerShell files to scan."

          $anyErrors = $false

          foreach ($file in $files) {
              Write-Host "Analyzing: $($file.FullName)..." -NoNewline
              $results = Invoke-ScriptAnalyzer -Path $file.FullName -Severity Error

              if ($results) {
                  Write-Host " [FAILED]" -ForegroundColor Red
                  $results | Format-Table
                  $anyErrors = $true
              } else {
                  Write-Host " [PASSED]" -ForegroundColor Green
              }
          }

          if ($anyErrors) { exit 1 }
